# Generated by Django 4.1.7 on 2023-03-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('club', models.TextField()),
                ('position', models.TextField()),
                ('home_location', models.TextField()),
                ('years_played', models.IntegerField()),
            ],
        ),
    ]
